In [1]:
import gymnasium as gym
import numpy as np
import random

In [2]:
alpha = 0.5
gamma = 0.99
episodes = 500
epsilon = 0.1

In [3]:
Q = np.zeros((48,4))
Q

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],


In [4]:
def epsilon_greedy(state):
    if random.random() < epsilon:
        return env.action_space.sample()
    else:
        return np.argmax(Q[state])

In [5]:
for episode in range(episodes):
    render = (episode %50 == 0)
    if render :
        env = gym.make("CliffWalking-v1", render_mode ='human')
        print(f"rendering at {episode+1}")
    else:
        env = gym.make("CliffWalking-v1")
    done = False
    state, _ = env.reset()
    
    total_rewards = 0
    episode_len = 0

    while not done:
        action = epsilon_greedy(state)    
        next_state, reward, terminated, truncated , _ = env.step(action)
        done = terminated or  truncated
        # Q learning updation condition
        Q[state, action] += alpha * (reward + gamma* np.max( Q[next_state] -  Q[state, action]))

        state = next_state
        episode_len +=1
        total_rewards += reward

    print(f"Episode = {episode} : total_rewards = {total_rewards}, episode_length = {episode_len}")
    env.close()

rendering at 1
Episode = 0 : total_rewards = -610, episode_length = 214
Episode = 1 : total_rewards = -1305, episode_length = 414
Episode = 2 : total_rewards = -43, episode_length = 43
Episode = 3 : total_rewards = -155, episode_length = 56
Episode = 4 : total_rewards = -38, episode_length = 38
Episode = 5 : total_rewards = -76, episode_length = 76
Episode = 6 : total_rewards = -57, episode_length = 57
Episode = 7 : total_rewards = -46, episode_length = 46
Episode = 8 : total_rewards = -54, episode_length = 54
Episode = 9 : total_rewards = -35, episode_length = 35
Episode = 10 : total_rewards = -71, episode_length = 71
Episode = 11 : total_rewards = -25, episode_length = 25
Episode = 12 : total_rewards = -131, episode_length = 32
Episode = 13 : total_rewards = -40, episode_length = 40
Episode = 14 : total_rewards = -32, episode_length = 32
Episode = 15 : total_rewards = -134, episode_length = 35
Episode = 16 : total_rewards = -27, episode_length = 27
Episode = 17 : total_rewards = -24,

In [6]:
# What did our agent learn

env = gym.make("CliffWalking-v1", render_mode ='human')
state ,_ = env.reset()
total_rewards = 0
episode_len = 0
done = False

while not done:
    action = np.argmax(Q[state])
    next_state , reward, terminated, truncated , _ = env.step(action)
    done = terminated or  truncated
    state = next_state
    episode_len +=1
    total_rewards += reward
print(f"total_reward = {total_rewards} & episode_length = {episode_len}")
env.close()

total_reward = -13 & episode_length = 13


In [7]:
Q[36]

array([  -6.56565657, -107.07070707,   -7.07070707,   -7.07070707])

In [8]:
Q[35]

array([-1.51515152, -1.01010101, -0.50505051, -1.51515152])

In [9]:
Q[24]

array([-7.07070707, -6.06060606, -7.07070707, -6.56565657])

In [10]:
Q[30]

array([  -4.04040404,   -3.03030303, -107.07070707,   -4.04040404])